### ISSUE TITLE
* User Auth

### ISSUE THREAD

**Issue by mikelduffy** [Resourceful-Redwoods/AspiringAspen#35]

**Comment by Rickapod** [comment]
1.) refactor for sign in pop up
2.) separate sign in and sign up to individual forms
     - sign up
              - check for existing username
3.) refactor for password
    - modify user model
    - refactor to sign in and up forms for passwords
                 - add password field to sign in
                 - add password and password confirmation fields to sign up form
    - implement password hash and check
4.) refactor for web tokens
5.) implement log out btn
